import { Router } from 'express';
import * as controller from '../controllers/adminController.js';
import { requireAuth, requireRoles } from '../middleware/authMiddleware.js';
import asyncHandler from '../wrapper.js';
const router = Router();
router.use(requireAuth, requireRoles('admin', 'barber', 'gerente'));
router.get('/admin/barbers', asyncHandler(controller.listShops));
router.patch('/admin/barbers/:id/access', asyncHandler(controller.updateAccess));
router.post('/admin/barbers/:id/password-reset', asyncHandler(controller.resetPassword));
router.post('/admin/barbers', asyncHandler(controller.createAccount));
router.put('/admin/barbers/:id/settings', asyncHandler(controller.updateSettings));
router.post('/admin/barbers/:id/payment', asyncHandler(controller.markPaid));
router.delete('/admin/barbers/:id', asyncHandler(controller.deleteAccount));
export default router;
