import { Router } from 'express';
import * as controller from '../controllers/appointmentController.js';
import { requireAuth } from '../middleware/authMiddleware.js';
import asyncHandler from '../wrapper.js';
const router = Router();
router.get('/appointments', requireAuth, asyncHandler(controller.listAppointments));
router.get('/appointments/availability', requireAuth, asyncHandler(controller.availability));
router.post('/appointments', requireAuth, asyncHandler(controller.createAppointment));
router.patch('/appointments/:id', requireAuth, asyncHandler(controller.updateAppointment));
router.delete('/appointments/:id', requireAuth, asyncHandler(controller.deleteAppointment));
export default router;
