import { Router } from 'express';
import * as controller from '../controllers/authController.js';
import { requireAuth } from '../middleware/authMiddleware.js';
import asyncHandler from '../wrapper.js';
const router = Router();
router.post('/auth/login', asyncHandler(controller.login));
router.post('/auth/signup', asyncHandler(controller.signup));
router.get('/auth/me', requireAuth, asyncHandler(controller.me));
router.post('/auth/change-password', requireAuth, asyncHandler(controller.changePassword));
router.post('/auth/accept-terms', requireAuth, asyncHandler(controller.acceptTerms));
export default router;
