import { Router } from 'express';
import * as controller from '../controllers/operationsController.js';
import { requireAuth, requireRoles } from '../middleware/authMiddleware.js';
import asyncHandler from '../wrapper.js';

const router = Router();
router.use(requireAuth);
router.get('/operations/wallet', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.wallet));
router.patch('/operations/wallet/:id', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.walletAction));
router.get('/operations/pending', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.pending));
router.patch('/operations/pending/:id', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.pendingAction));
router.get('/operations/commissions', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.commissions));
router.get('/operations/retention', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.retention));
router.get('/operations/cash', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.cash));
router.post('/operations/cash/entries', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.createCashEntry));
router.delete('/operations/cash/entries/:id', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.deleteCashEntry));
router.get('/operations/profile', asyncHandler(controller.profile));
router.patch('/operations/profile', asyncHandler(controller.updateProfile));
router.get('/operations/hours', asyncHandler(controller.hours));
router.patch('/operations/hours', asyncHandler(controller.updateHours));
router.get('/operations/whatsapp', requireRoles('admin', 'gerente', 'manager', 'owner'), asyncHandler(controller.whatsapp));
export default router;
