import 'package:flutter/material.dart';
import 'view_models/agenda_view_model.dart';
import '../core/widgets/zen_card.dart';
import '../core/widgets/zen_page.dart';
import '../core/theme/zen_colors.dart';
class AgendaScreen extends StatefulWidget { const AgendaScreen({super.key, required this.viewModel}); final AgendaViewModel viewModel; @override State<AgendaScreen> createState() => _AgendaScreenState(); }
class _AgendaScreenState extends State<AgendaScreen> { @override void initState() { super.initState(); widget.viewModel..addListener(_refresh)..load(); } void _refresh() { if (mounted) setState(() {}); } @override void dispose() { widget.viewModel.removeListener(_refresh); super.dispose(); }
  @override Widget build(BuildContext context) { if (widget.viewModel.loading && widget.viewModel.items.isEmpty) return const Center(child: CircularProgressIndicator()); return RefreshIndicator(onRefresh: () => widget.viewModel.load(), child: ZenPage(title:'Agenda premium',children:[if(widget.viewModel.error!=null) ZenCard(child:Text(widget.viewModel.error!)),if(widget.viewModel.items.isEmpty)const ZenEmptyState(message:'Nenhum horário para este dia',icon:Icons.calendar_today),...widget.viewModel.items.map((item)=>Padding(padding:const EdgeInsets.only(bottom:10),child:ZenCard(child:ListTile(contentPadding:EdgeInsets.zero,leading:Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:ZenColors.green.withValues(alpha:.12),borderRadius:BorderRadius.circular(14)),child:Text(item.time,style:const TextStyle(fontWeight:FontWeight.w900))),title:Text(item.clientName,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${item.date} · ${item.serviceName}',style:const TextStyle(color:ZenColors.muted)),trailing:item.status=='finalizado'?const ZenStatusPill(label:'Concluído',color:ZenColors.green):FilledButton(onPressed:()=>widget.viewModel.finish(item),child:const Text('Finalizar'))))))])); }
}
